services:
  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    user: root
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=agent-1

  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#  - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=agent-2
