networks:
  teamcity_network:
    driver: bridge

services:                                                                                                                                   M     
  teamcity:
    image: jetbrains/teamcity-server
    user: root
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    networks:
      - teamcity_network

  teamcity-agent:
    image: jetbrains/teamcity-agent
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=regular_agent
    networks:
      - teamcity_network

  teamcity-minimal-agent:
    image: jetbrains/teamcity-minimal-agent
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=minimal-agent
    networks:
      - teamcity_network
